sudo: false
language: java
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.m2'
        - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: "mkarpisek-github"

install: true
script: mvn clean verify sonar:sonar -P unit -P jacoco

after_success:
    - bash <(curl -s https://codecov.io/bash)
