sudo: false
language: java
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.m2

install: true
script: mvn clean verify -P unit -P jacoco

after_success:
    - bash <(curl -s https://codecov.io/bash)
